# -----------------------------------------------------------------------------
# API GATEWAY CONFIGURATION
# -----------------------------------------------------------------------------
server:
  port: 8000

spring:
  cloud:
    gateway:
      httpServer:
        wiretap: true
      httpclient:
        wiretap: true
      server:
        webflux:
          routes:
            # ------------------------------------------------------
            # AUTHENTICATION SERVICE
            # ------------------------------------------------------
            - id: auth-service-route
              uri: lb://authentication-service
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=2

            # ------------------------------------------------------
            # TENANT SERVICE (tenant registration, etc.)
            # ------------------------------------------------------
            - id: tenant-service-route
              uri: lb://tenant-service
              predicates:
                - Host=localhost,localhost:**,www.localhost,www.localhost:**,jibramed.com,www.jibramed.com
                - Path=/api/v1/tenants/**
              filters:
                - StripPrefix=2

            # ------------------------------------------------------
            # SUBSCRIPTION SERVICE (subscription registration, etc.)
            # ------------------------------------------------------
            - id: subscription-service-route
              uri: lb://subscription-service
              predicates:
                - Host=localhost,localhost:**,www.localhost,www.localhost:**,jibramed.com,www.jibramed.com
                - Path=/api/v1/modules/**,/api/v1/subscriptions/**,/api/v1/plans/**
              filters:
                - StripPrefix=2

            # ------------------------------------------------------
            # PLATFORM USER SERVICE (for jibramed.com or www.jibramed.com)
            # ------------------------------------------------------
            - id: platformuser-service-route
              uri: lb://platformuser-service
              predicates:
                - Host=localhost,localhost:**,www.localhost,www.localhost:**,jibramed.com,www.jibramed.com
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=2
                - RemoveRequestHeader=X-Tenant-ID

            # ------------------------------------------------------
            # TENANT USER SERVICE (for hospital subdomains)
            # ------------------------------------------------------
            - id: tenantuser-service-route
              uri: lb://tenantuser-service
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=2
                - PreserveHostHeader=true

            # ------------------------------------------------------
            # SCHEMA SERVICE (schema registration, etc.)
            # ------------------------------------------------------
            - id: schema-service-route
              uri: lb://schema-service
              predicates:
                - Path=/api/v1/schemas/**
              filters:
                - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
  endpoint:
    gateway:
      access: unrestricted
