# -----------------------------------------------------------------------------
# API GATEWAY CONFIGURATION
# -----------------------------------------------------------------------------
server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: test-route
          uri: https://httpbin.org
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        # ------------------------------------------------------
        # AUTHENTICATION SERVICE
        # ------------------------------------------------------
        - id: auth-service-route
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2

        # ------------------------------------------------------
        # PLATFORM USER SERVICE (for jibramed.com or www.jibramed.com)
        # ------------------------------------------------------
        - id: platformuser-service-route
          uri: lb://PLATFORMUSER-SERVICE
          predicates:
            - Host=jibramed.com,www.jibramed.com,localhost,www.localhost
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
            - RemoveRequestHeader=X-Tenant-ID

        # ------------------------------------------------------
        # TENANT USER SERVICE (for hospital subdomains)
        # ------------------------------------------------------
        - id: tenantuser-service-route
          uri: lb://TENANTUSER-SERVICE
          predicates:
            - Host=**.jibramed.com,**.localhost
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
            - PreserveHostHeader=true

        # ------------------------------------------------------
        # TENANT SERVICE (tenant registration, etc.)
        # ------------------------------------------------------
        - id: tenant-service-route
          uri: lb://TENANT-SERVICE
          predicates:
            - Path=/api/v1/tenants/**
          filters:
            - StripPrefix=2

        # ------------------------------------------------------
        # HOSPITAL SERVICE
        # ------------------------------------------------------
        - id: hospital-service-route
          uri: lb://HOSPITAL-SERVICE
          predicates:
            - Path=/api/v1/hospitals/**
          filters:
            - StripPrefix=2

# -----------------------------------------------------------------------------
# LOGGING AND MANAGEMENT
# -----------------------------------------------------------------------------
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: TRACE

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
  endpoint:
    gateway:
      access: unrestricted
