# -----------------------------------------------------------------------------
# API GATEWAY CONFIGURATION
# -----------------------------------------------------------------------------
server:
  port: 8080

spring:
  cloud:
    gateway:
      httpServer:
        wiretap: true
      httpclient:
        wiretap: true

      server:
        webflux:
          routes:
            # ======================================================================
            # == GROUP 2: PLATFORM-ONLY ROUTES
            # ======================================================================
            - id: platform_routes
              uri: no://op
              predicates:
                - Host=app.jibramed.com, localhost:**
              filters:
                - StripPrefix=2 # /api/v1/ -> /
              routes:
                # --- AUTH SERVICE (for platform users) ---
                - id: platform_auth_route
                  uri: lb://AUTHENTICATION-SERVICE
                  predicates:
                    - Path=/api/v1/auth/**

                # --- PLATFORM USER SERVICE ---
                - id: platform_user_route
                  uri: lb://PLATFORMUSER-SERVICE
                  predicates:
                    - Path=/api/v1/users/**
                  filters:
                    # This route is for platform, so we ensure no tenant key is passed
                    - RemoveRequestHeader=X-Tenant-Key

                # --- TENANT SERVICE (Platform-only) ---
                - id: tenant_service_route
                  uri: lb://TENANT-SERVICE
                  predicates:
                    - Path=/api/v1/tenants/**

                # --- SUBSCRIPTION SERVICE (Platform-only) ---
                - id: subscription_service_route
                  uri: lb://SUBSCRIPTION-SERVICE
                  predicates:
                    - Path=/api/v1/modules/**, /api/v1/subscriptions/**, /api/v1/plans/**

            # ======================================================================
            # == GROUP 2: TENANT-ONLY ROUTES
            # ======================================================================
            - id: tenant_routes
              uri: no://op
              predicates:
                - Host=*.jibramed.com, *.localhost:**
              filters:
                - StripPrefix=2 # /api/v1/ -> /
                - PreserveHostHeader=true
              routes:
                # --- AUTH SERVICE (for tenant users) ---
                - id: tenant_auth_route
                  uri: lb://AUTHENTICATION-SERVICE
                  predicates:
                    - Path=/api/v1/auth/**

                # --- TENANT USER SERVICE ---
                - id: tenant_user_route
                  uri: lb://TENANTUSER-SERVICE
                  predicates:
                    - Path=/api/v1/users/**

                # --- HOSPITAL SERVICE ---
                - id: hospital_service_route
                  uri: lb://HOSPITAL-SERVICE
                  predicates:
                    - Path=/api/v1/hospitals/**

# Management endpoint configuration
management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
  endpoint:
    gateway:
      access: unrestricted
