# -----------------------------------------------------------------------------
# API GATEWAY CONFIGURATION
# -----------------------------------------------------------------------------
server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # ------------------------------------------------------
            # AUTHENTICATION SERVICE
            # ------------------------------------------------------
            - id: auth-service-route
              uri: lb://AUTHENTICATION-SERVICE
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=2

            # ------------------------------------------------------
            # TENANT SERVICE (tenant registration, etc.)
            # ------------------------------------------------------
            - id: tenant-service-route
              uri: lb://TENANT-SERVICE
              predicates:
                - Path=/api/v1/tenants/**
              filters:
                - StripPrefix=2

            # ------------------------------------------------------
            # SUBSCRIPTION SERVICE (subscription registration, etc.)
            # ------------------------------------------------------
            - id: subscription-service-route
              uri: lb://SUBSCRIPTION-SERVICE
              predicates:
                - Path=/api/v1/modules/**
              filters:
                - StripPrefix=2

            # ------------------------------------------------------
            # PLATFORM USER SERVICE (for jibramed.com or www.jibramed.com)
            # ------------------------------------------------------
            - id: platformuser-service-route
              uri: lb://PLATFORMUSER-SERVICE
              predicates:
                - Host=localhost,localhost:8080,www.localhost,www.localhost:8080,jibramed.com,www.jibramed.com
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=2
                - RemoveRequestHeader=X-Tenant-ID

            # ------------------------------------------------------
            # TENANT USER SERVICE (for hospital subdomains)
            # ------------------------------------------------------
            - id: tenantuser-service-route
              uri: lb://TENANTUSER-SERVICE
              predicates:
                - Host=**.jibramed.com,**.localhost,**.localhost:8080
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=2
                - PreserveHostHeader=true

            # ------------------------------------------------------
            # HOSPITAL SERVICE
            # ------------------------------------------------------
            - id: hospital-service-route
              uri: lb://HOSPITAL-SERVICE
              predicates:
                - Path=/api/v1/hospitals/**
              filters:
                - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
  endpoint:
    gateway:
      access: unrestricted
