# -----------------------------------------------------------------------------
# API GATEWAY CONFIGURATION
# -----------------------------------------------------------------------------
server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - RemoveResponseHeader=Server
        - RemoveResponseHeader=X-Powered-By

      routes:
        # ------------------------------------------------------
        # AUTH SERVICE
        # ------------------------------------------------------
        - id: auth-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2

        # ------------------------------------------------------
        # PLATFORM USER SERVICE (jibramed.com / localhost)
        # ------------------------------------------------------
        - id: platformuser-service
          uri: lb://PLATFORMUSER-SERVICE
          predicates:
            - Host=localhost, www.localhost, jibramed.com, www.jibramed.com
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
            - RemoveRequestHeader=X-Tenant-ID

        # ------------------------------------------------------
        # TENANT USER SERVICE (subdomains)
        # ------------------------------------------------------
        - id: tenantuser-service
          uri: lb://TENANTUSER-SERVICE
          predicates:
            - Host=**.jibramed.com, **.localhost
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2
            - PreserveHostHeader=true

        # ------------------------------------------------------
        # TENANT SERVICE
        # ------------------------------------------------------
        - id: tenant-service
          uri: lb://TENANT-SERVICE
          predicates:
            - Path=/api/v1/tenants/**
          filters:
            - StripPrefix=2

        # ------------------------------------------------------
        # HOSPITAL SERVICE
        # ------------------------------------------------------
        - id: hospital-service
          uri: lb://HOSPITAL-SERVICE
          predicates:
            - Path=/api/v1/hospitals/**
          filters:
            - StripPrefix=2

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
  endpoint:
    gateway:
      access: unrestricted
