# -----------------------------------------------------------------------------
# API GATEWAY CONFIGURATION
# -----------------------------------------------------------------------------
server:
  # The public-facing port for the entire application.
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        # Route for Tenant Service
        - id: tenant-service-route
          uri: lb://TENANT-SERVICE # "lb" means load-balanced via Eureka
          predicates:
            - Path=/api/v1/tenants/**
          filters:
            # Strips the first 2 path segments (/api/v1) before forwarding.
            # So, /api/v1/tenants/1 -> /tenants/1
            - StripPrefix=2

        # Route for Authentication Service
        - id: auth-service-route
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2

        # Route for Hospital Service
        - id: hospital-service-route
          uri: lb://hospital-service
          predicates:
            - Path=/api/v1/hospitals/**
          filters:
            - StripPrefix=2
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
