# -----------------------------------------------------------------------------
# PLATFORM USER SERVICE CONFIGURATION
# -----------------------------------------------------------------------------
server:
  port: 18112 # Example port for this service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jibramed-his-platform-db # Make sure this is your correct DB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    hibernate:
      # This tells Hibernate to check the schema, but not create/update it.
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    # ✅ THE FIX: This property tells Spring to run Flyway BEFORE Hibernate validation.
    defer-datasource-initialization: true

  flyway:
    # Ensures Flyway runs and manages the schema.
    enabled: true
    # The location of your SQL migration scripts.
    locations: classpath:db/migration

# You would also have your Eureka client config here...
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
