# -----------------------------------------------------------------------------
# PLATFORM USER SERVICE CONFIGURATION
# -----------------------------------------------------------------------------
server:
  port: 19111

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jibramed-his-platform-db # Make sure this is your correct DB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    # This tells Hibernate to check the schema, but not create/update it.
    # ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  flyway:
    baseline-on-migrate: true
    # The location of your SQL migration scripts.
    locations: classpath:db/migration

# You would also have your Eureka client config here...
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
