# -----------------------------------------------------------------------------
# TENANT USER SERVICE CONFIGURATION
# -----------------------------------------------------------------------------
server:
  port: 18211

spring:
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        max-interval: 200
        multiplier: 1.1
        initial-interval: 100

# Logging Configuration
logging:
  level:
    com.his.jibramed: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

# Custom application-specific properties
app:
  tenant:
    db:
      default-db-prefix: tenant_
      create-db-on-register: true
      admin-username: postgres
      admin-password: root
      admin-url: jdbc:postgresql://localhost:5432/postgres
