server:
  port: 18211

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  tenant:
    db:
      default-db-prefix: tenant_
      create-db-on-register: true
      admin-username: postgres
      admin-password: root
      admin-url: jdbc:postgresql://localhost:5432/postgres
