# Tenant Service
server:
  port: 18111

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jibramed-his-platform-db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    locations: classpath:db/migration/platform
