# -----------------------------------------------------------------------------
# TENANT USER SERVICE CONFIGURATION
# -----------------------------------------------------------------------------
server:
  port: 18211

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tenant_jibramed_general
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        max-interval: 2000
        multiplier: 1.1
        initial-interval: 1000

# Logging Configuration
logging:
  level:
    com.his.jibramed: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

# Custom application-specific properties
app:
  tenant:
    default-db-prefix: tenantuser_
    create-db-on-register: true
    db-admin-user: postgres
    db-admin-password: root
